### ISSUE TITLE
Large transactions are not being broadcasted

### ISSUE THREAD

**Issue by merc1er** [ActorForth/bch-toolkit#34]
Large transactions (tried with 43 and 47 UTXOs) are not being broadcasted by https://rest.bch.actorforth.org/#/rawtransactions/sendRawTransactionSingle.

The same transaction was broadcasted fine by this API: https://insomnia.fountainhead.cash/v1/tx/broadcast. See docs [here](https://insomnia.fountainhead.cash).

**Comment by scherrey** [comment]
Issue only occurs when using a GET request to transmit a tx. POST requests succeed. It's actually completely inappropriate to use GET to push non-idempotent requests in REST. We should discourage this and ultimate deprecate support for such behavior. 

Anticipate a review of serious REST violations like this on the legacy platform and release a new API version increment that enforces proper use of the HTTP verbs. We can leave "support" of the old version for some time but keep the new one strict - eventually turning off support for the old legacy version.
